spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service_dev
    username: dev_user
    password: dev_pass
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true